server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~ \.jsx$ {
        default_type application/javascript;
        charset utf-8;
    }

    location ~* \.(css|js|png|jpg|jpeg|gif|webp|svg|ico)$ {
        expires 7d;
        add_header Cache-Control "public";
    }

    gzip on;
    gzip_types text/css application/javascript text/javascript application/json image/svg+xml;
}
